name: CI/CD Pipeline test

permissions:
  contents: read
  pull-requests: write
  issues: write
  
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Te permite seguir probándolo manualmente si quieres

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      # 1. Notificación de Inicio (Solo en Pull Requests)
      - name: Comentar inicio
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'CI/CD en acción. Ejecutando tareas …'
            })

      # 2. Ejecución del bloque de pruebas de pytest
      - name: Ejecutar pruebas
        env:
          PYTHONPATH: .
        run: |
          pytest

      # 3. Notificación de Éxito Final (Solo en PR)
      - name: Comentar éxito final
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'CI/CD terminado con éxito.'
            })